// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type GalleryImage struct {
	Src      string
	Alt      string
	Category string
}

var galleryImages = []GalleryImage{
	{Src: "/images/gallery/construction-site-1.jpg", Alt: "Construction site overview", Category: "Construction"},
	{Src: "/images/gallery/construction-site-2.jpg", Alt: "Building under construction", Category: "Construction"},
	{Src: "/images/gallery/construction-site-3.jpg", Alt: "Construction progress", Category: "Construction"},
	{Src: "/images/gallery/concrete-pour-1.jpg", Alt: "Concrete pouring", Category: "Concrete"},
	{Src: "/images/gallery/concrete-work-1.jpg", Alt: "Concrete finishing work", Category: "Concrete"},
	{Src: "/images/gallery/concrete-finishing.jpg", Alt: "Concrete surface finishing", Category: "Concrete"},
	{Src: "/images/gallery/foundation-work.jpg", Alt: "Foundation construction", Category: "Foundation"},
	{Src: "/images/gallery/excavator-work.jpg", Alt: "Excavator at work", Category: "Excavation"},
	{Src: "/images/gallery/heavy-equipment.jpg", Alt: "Heavy construction equipment", Category: "Equipment"},
	{Src: "/images/gallery/building-frame.jpg", Alt: "Building frame structure", Category: "Construction"},
	{Src: "/images/gallery/worker-welding.jpg", Alt: "Worker welding steel", Category: "Steel Work"},
	{Src: "/images/gallery/steel-structure.jpg", Alt: "Steel building structure", Category: "Steel Work"},
	{Src: "/images/gallery/crane-work.jpg", Alt: "Crane lifting materials", Category: "Equipment"},
	{Src: "/images/gallery/commercial-building.jpg", Alt: "Commercial building exterior", Category: "Commercial"},
	{Src: "/images/gallery/barn-construction.jpg", Alt: "Agricultural barn", Category: "Agricultural"},
	{Src: "/images/gallery/site-grading.jpg", Alt: "Site grading work", Category: "Excavation"},
	{Src: "/images/gallery/residential-build.jpg", Alt: "Residential construction", Category: "Residential"},
	{Src: "/images/gallery/bulldozer-work.jpg", Alt: "Bulldozer clearing land", Category: "Excavation"},
	{Src: "/images/gallery/workers-site.jpg", Alt: "Construction workers on site", Category: "Team"},
}

func PhotoGallery() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"relative py-16 lg:py-24 bg-[#050505] overflow-hidden\"><div class=\"absolute inset-0 blueprint-grid opacity-20\"></div><div class=\"relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\"><div class=\"text-center mb-12\"><div class=\"flex items-center justify-center gap-3 mb-4\"><div class=\"w-12 h-[3px] bg-gradient-to-r from-green-600 to-green-500\"></div><span class=\"text-green-500 text-sm font-semibold uppercase tracking-wider\">Our Work</span><div class=\"w-12 h-[3px] bg-gradient-to-l from-green-600 to-green-500\"></div></div><h2 class=\"font-poppins text-3xl lg:text-4xl font-bold text-white mb-4\">Project <span class=\"text-green-400\">Gallery</span></h2><p class=\"text-white/60 max-w-2xl mx-auto\">Browse through our portfolio of completed construction, concrete, and excavation projects.</p></div><div class=\"grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, image := range galleryImages {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 templ.SafeURL
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(image.Src))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/gallery.templ`, Line: 55, Col: 37}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" class=\"group relative aspect-square overflow-hidden border-2 border-green-600/20 hover:border-green-500/50 transition-all duration-300 rounded-lg shadow-md\" target=\"_blank\"><img src=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(image.Src)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/gallery.templ`, Line: 60, Col: 22}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" alt=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(image.Alt)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/gallery.templ`, Line: 61, Col: 22}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" class=\"w-full h-full object-cover transition-transform duration-500 group-hover:scale-110\" loading=\"lazy\"><div class=\"absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300\"></div><div class=\"absolute bottom-0 left-0 right-0 p-4 translate-y-full group-hover:translate-y-0 transition-transform duration-300\"><span class=\"inline-block px-2 py-1 bg-green-600/90 text-white text-xs font-semibold uppercase tracking-wider mb-1 rounded\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(image.Category)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/gallery.templ`, Line: 68, Col: 24}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span><p class=\"text-white text-sm font-medium\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(image.Alt)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/gallery.templ`, Line: 70, Col: 60}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</p></div></a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
